// <auto-generated />
using DIPLOMA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DIPLOMA.Migrations.ApplicationDbContext_2Migrations
{
    [DbContext(typeof(ApplicationDbContext_2))]
    [Migration("20190611181047_AddTableDerictoryClients")]
    partial class AddTableDerictoryClients
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DIPLOMA.Models.DirectoryClients", b =>
                {
                    b.Property<int>("DirectoryClientsID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressRegistration");

                    b.Property<string>("AddressResidential");

                    b.Property<string>("DataAboutWorkPlace");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<int>("PassportNumber");

                    b.Property<int>("PassportSerial");

                    b.Property<string>("Patronymic");

                    b.Property<string>("SecondName");

                    b.Property<string>("TelephoneNumber");

                    b.HasKey("DirectoryClientsID");

                    b.ToTable("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
